### PR TITLE
Bukkit extension for standalone config module.

### LINKED ISSUE #9: Add extra module for standalone config module.

### PR DESCRIPTION
**Pull request by portlek**
Closes #9

### CODE REVIEW

**Comment by portlek** [comment]
I don't know maybe it's a stupid idea

**Comment by portlek** [comment]
Or just change the dependency of bukkit-config-extra module with bukkit-config.

**Review by HSGamer — CHANGES_REQUESTED** [review]
You can just use `HSCore-config` as a dependency for `HSCore-bukkit-config-extra`
I'll remove `HSCore-bukkit-config` in the near update

**Comment by portlek** [comment]
Alright that's fine.

**Review by HSGamer — APPROVED** [review]

**Pull request merged**
