### PR TITLE
More detailed Javadocs for addon modules.

### PR DESCRIPTION
**Pull request by portlek**
- Added package-info
- Added More Javadocs
- Added More this and final keyword.
- Removed redundant final keywords from methods.
- More compact view.
- Method alignment in terms of visibility.

### CODE REVIEW

**Comment by HSGamer** [comment]
Have you changed the code style ?

**Comment by portlek** [comment]
Not exactly

**Comment by portlek** [comment]
Just some this and final keywords, and added some missing Javadoc that's it.

**Review by HSGamer — APPROVED** [review]

**Comment by portlek** [comment]
I'm using a [code style](https://github.com/shiruka/codestyle) which is here.

**Pull request merged**
